S3DF Build Fixes
slaclab/evrma pull request #1
Opened 2024-07-23 04:00 UTC by JJL772

* Build against R1.0.12 of evrmaDriver (this is a pending release with rhel9 support)
* Add support for rhel9
* Use PACKAGE_TOP instead of absolute path to allow building in S3DF
* Add macro for evrmaDriver version

2025-02-06 23:47 UTC, marciodo requested changes
Please, update the README.build file:
- Add information about INSTALL_LOCATION for architectures not mentioned in the current README.
- Add instruction that the EPICS_PACKAGE_TOP environment variable must be set properly before building. I believe that the instruction about KERNEL_MODULE_EVRMA should be removed from README if we are not using the hardcoded paths anymore.

Please, check if README.files is still current.

If creating a release, don't forget to update RELEASE_NOTES (I'm not saying that this pull request should necessarily trigger a change).

2025-02-07 01:45 UTC, JJL772 commented
Ok, applied all of those suggestions

2025-02-07 18:08 UTC, marciodo requested changes

2025-02-07 18:08 UTC, marciodo commented on README.build
> +Ensure that PACKAGE_SITE_TOP or EPICS_PACKAGE_TOP are set in your environment or on the command line.
Please explain that these variables need to point to the location of the kernel module EVRMA.

2025-02-07 18:08 UTC, marciodo commented on README.build
> +The following variables should or can be changed to match your target configuration:
I think we need to make it more explicit that this is an optional (and rare) step, only if the person is testing a customized target.

2025-02-07 18:56 UTC, marciodo approved these changes

2025-02-07 18:56 UTC, merged